### ISSUE TITLE
No code actions available

### ISSUE THREAD

**Issue by BartPermentier** [wbrakowski/AL-Navigator#32] opened 2020-05-25 14:45 UTC
Hey,

Love the concept of your extension! But it's not working for me.
![image](https://user-images.githubusercontent.com/24684493/82822972-fd522400-9ea6-11ea-9234-33eb62dcc00a.png)
I disabled all other extensions; am I missing anything?

Thanks!

**Comment by wbrakowski** [comment] 2020-05-25 19:08
Hey BartPermentier,

I have had this issue 2-3x with freshly created projects, but it always worked after reopening Visual Studio Code. Two questions from my side:

1. Are the code actions still not available after you reopen Visual Studio Code?
2. Are the code actions available for already existing Visual Studio Code projects?

 I will definitely investigate this further and figure out what is going on there.

Thanks for reporting!

**Comment by BartPermentier** [comment] 2020-05-27 07:34
Hey,

1. Yes I re-opened multiple times.
2. It doesn't work in existing projects either, that's why I created this small project.

**Update**: after opening an closing VSCode about 5 times it finally worked in new and existing projects.

Very weird...
Thanks for the help and sorry for the inconvenience!

**Comment by wbrakowski** [comment] 2020-05-27 14:28
Glad to hear that it works now :-)
I keep this issue open for a while until I have investigated it more. 

Have a nice week.

**Comment by wbrakowski** [comment] 2020-05-29 08:19
I unfortunately could not reproduce this. Therefore, I will close this issue for now. If other people report similiar issues, then I will investigate further.

**Closed by wbrakowski** 2020-05-29 08:19 UTC
Labels: bug

**Comment by BartPermentier** [comment] 2020-05-29 08:45
Hey,

I think it might have something todo with the poor performance of my laptop. This extensions is heavily reliant on the CodeCop warnings so when my Ram is full I'm having the same issue.

So anyone else experiencing this issue just close your 100tabs browser ;)
